use crate::cli::*;
use anyhow::Result;
use standx_maker::{
    self as maker, Alert, AlertMonitor, MakerConfig, MakerStats, RestingQuote, VolBreaker,
};
use standx_sdk::auth::Credentials;
use standx_sdk::client::StandXClient;
use standx_sdk::error::Error as StandxError;
use standx_sdk::models::{Order, OrderSide};
use standx_sdk::order_response::OrderResponse;
use std::collections::{HashMap, HashSet};
use std::time::Duration;
use tokio::signal;

mod config;
mod cycle;
mod feed;
mod output;

use cycle::{cancel_maker_orders_with_retry, maker_cycle};
use feed::{market_snapshot, spawn_market_feed};

// ============================================================================
// Maker bot (SIP-5A community maker yield)
// ============================================================================

/// Env var gating live order placement. The live path ships code-complete but
/// locked until it has been supervised-tested against production.
const LIVE_MAKER_ENV: &str = "STANDX_ENABLE_LIVE_MAKER";
/// Prefix reserved for orders generated by this maker command. Never use it
/// for hand-entered orders: the maker may cancel any order bearing this tag.
const MAKER_CL_ORD_ID_PREFIX: &str = "sxmk-";

/// Why the maker loop stopped.
enum MakerExit {
    CtrlC,
    /// The asynchronous order-response stream cannot confirm live orders.
    OrderResponse(String),
    /// Three consecutive transient maker-cycle failures.
    ConsecutiveErrors(String),
}

impl MakerExit {
    fn lifecycle_reason(&self) -> String {
        match self {
            Self::CtrlC => "Ctrl+C".to_string(),
            Self::OrderResponse(error) => {
                format!("fail-safe: order-response stream unavailable: {error}")
            }
            Self::ConsecutiveErrors(error) => {
                format!("fail-safe: 3 consecutive maker cycle errors: {error}")
            }
        }
    }

    fn terminal_error(&self) -> Option<String> {
        match self {
            Self::CtrlC => None,
            Self::OrderResponse(error) => Some(format!(
                "maker stopped immediately (fail-safe): order-response stream unavailable: {error}"
            )),
            Self::ConsecutiveErrors(error) => Some(format!(
                "maker stopped after 3 consecutive maker cycle errors (fail-safe): {error}"
            )),
        }
    }
}

/// Pending place awaiting order-id adoption in live mode. The HTTP request is
/// correlated to its asynchronous response by request ID, then to the visible
/// open order by client order ID. Side, price, and quantity remain only as a
/// compatibility fallback for orders submitted before client IDs were added.
struct PendingPlace {
    request_id: String,
    cl_ord_id: String,
    side: OrderSide,
    price: f64,
    qty: f64,
    level: u32,
    ref_center: f64,
    cycle: u64,
}

/// Whether an exchange order was created by this maker command.
fn is_maker_order(order: &Order) -> bool {
    order
        .cl_ord_id
        .as_deref()
        .is_some_and(|id| id.starts_with(MAKER_CL_ORD_ID_PREFIX))
}

/// A submitted placement reserves its `(side, level)` until it is either
/// rejected, visible as an open order, or times out. This stops polling lag
/// from turning one desired quote into multiple real orders.
fn pending_covers_slot(pending: &[PendingPlace], side: OrderSide, level: u32) -> bool {
    pending
        .iter()
        .any(|place| place.side == side && place.level == level)
}

fn apply_order_responses(
    receiver: &mut tokio::sync::mpsc::Receiver<OrderResponse>,
    pending: &mut Vec<PendingPlace>,
    output_format: OutputFormat,
    symbol: &str,
    cycle: u64,
    price_decimals: u32,
) -> Result<()> {
    loop {
        let response = match receiver.try_recv() {
            Ok(response) => response,
            Err(tokio::sync::mpsc::error::TryRecvError::Empty) => return Ok(()),
            Err(tokio::sync::mpsc::error::TryRecvError::Disconnected) => {
                return Err(anyhow::anyhow!(
                    "order-response stream disconnected; refusing further live orders"
                ));
            }
        };
        let Some(request_id) = response.request_id.as_deref() else {
            continue;
        };
        let Some(index) = pending
            .iter()
            .position(|place| place.request_id == request_id)
        else {
            // Authentication acknowledgements and cancellation responses do
            // not correspond to a pending maker place.
            continue;
        };

        if response.accepted() {
            continue;
        }

        let rejected = pending.remove(index);
        output::log_maker_event(
            output_format,
            symbol,
            cycle,
            "place_rejected_async",
            rejected.side,
            rejected.level,
            rejected.price,
            price_decimals,
            &response.message,
        );
    }
}

/// A business rejection from the venue: the exchange responded with a
/// definite "no" (post-only would-cross, order not found, insufficient
/// margin, …). These are expected during normal quoting and must NOT trip
/// the fail-safe — that is reserved for transient failures (network, 5xx,
/// rate limit) that signal we can no longer talk to the exchange, which
/// keep their `retryable` flag and propagate as cycle errors.
fn is_order_rejection(e: &StandxError) -> bool {
    matches!(
        e,
        StandxError::Api {
            retryable: false,
            ..
        }
    )
}

/// Whether an open order's remaining `open_qty` plausibly belongs to a place
/// we made for `placed_qty`. A partial fill leaves a positive remainder no
/// larger than what we placed; anything bigger is somebody else's order.
/// Tolerating the shrink is what keeps a partially-filled order adopted
/// (and thus HELD) instead of cancelled as an unknown order.
fn open_qty_adopts(open_qty: f64, placed_qty: f64) -> bool {
    open_qty > 0.0 && open_qty <= placed_qty * (1.0 + 1e-6)
}

/// Shape a webhook body for the target chat platform. `text` is the ready
/// one-line message; `raw` is the full structured object used verbatim for
/// the `Raw` format (it must itself carry a `text` field).
fn webhook_body(
    format: AlertWebhookFormat,
    text: &str,
    raw: &serde_json::Value,
) -> serde_json::Value {
    match format {
        // Slack incoming webhook and Telegram sendMessage both read `text`
        // (Telegram takes chat_id/token from the URL).
        AlertWebhookFormat::Slack | AlertWebhookFormat::Telegram => {
            serde_json::json!({ "text": text })
        }
        // Feishu/Lark custom bot.
        AlertWebhookFormat::Feishu => serde_json::json!({
            "msg_type": "text",
            "content": { "text": text },
        }),
        // Generic consumers: the full structured object.
        AlertWebhookFormat::Raw => raw.clone(),
    }
}

/// POST a webhook body with a short timeout, logging failures. Awaitable so
/// callers can fire-and-forget (`tokio::spawn`) or await delivery (shutdown).
async fn post_webhook(client: reqwest::Client, url: String, body: serde_json::Value) {
    match client
        .post(&url)
        .json(&body)
        .timeout(Duration::from_secs(5))
        .send()
        .await
    {
        Ok(r) if !r.status().is_success() => {
            eprintln!("⚠️  maker webhook returned {}", r.status())
        }
        Err(e) => eprintln!("⚠️  maker webhook POST failed: {e}"),
        _ => {}
    }
}

/// Deliver a lifecycle notification (bot started / stopped) to the console
/// (JSON mode only — the banner/summary already cover table mode) and, if
/// configured, the webhook. `await_delivery` awaits the POST so the shutdown
/// message lands before the process exits.
#[allow(clippy::too_many_arguments)]
async fn notify_lifecycle(
    event: &str,
    text: &str,
    symbol: &str,
    output_format: OutputFormat,
    http: Option<&reqwest::Client>,
    webhook_url: &Option<String>,
    webhook_format: AlertWebhookFormat,
    await_delivery: bool,
) {
    let ts = chrono::Utc::now().to_rfc3339_opts(chrono::SecondsFormat::Secs, true);
    if output_format == OutputFormat::Json {
        println!(
            "{}",
            serde_json::json!({
                "ts": ts, "symbol": symbol, "action": "lifecycle",
                "event": event, "message": text,
            })
        );
    }
    if let (Some(client), Some(url)) = (http, webhook_url.as_ref()) {
        let raw = serde_json::json!({
            "text": text, "ts": ts, "symbol": symbol,
            "action": "lifecycle", "event": event,
        });
        let body = webhook_body(webhook_format, text, &raw);
        if await_delivery {
            post_webhook(client.clone(), url.clone(), body).await;
        } else {
            tokio::spawn(post_webhook(client.clone(), url.clone(), body));
        }
    }
}

#[allow(clippy::too_many_arguments)]
fn deliver_alert(
    alert: &Alert,
    symbol: &str,
    output_format: OutputFormat,
    http: Option<&reqwest::Client>,
    webhook_url: &Option<String>,
    webhook_format: AlertWebhookFormat,
) {
    let ts = chrono::Utc::now().to_rfc3339_opts(chrono::SecondsFormat::Secs, true);
    let label = if alert.firing {
        "🚨 ALERT"
    } else {
        "✅ RESOLVED"
    };

    match output_format {
        OutputFormat::Json => {
            println!(
                "{}",
                serde_json::json!({
                    "ts": ts, "symbol": symbol, "action": "alert",
                    "kind": alert.kind, "firing": alert.firing,
                    "message": alert.message,
                })
            );
        }
        _ => eprintln!("{} [{}] {} — {}", label, alert.kind, symbol, alert.message),
    }

    if let (Some(client), Some(url)) = (http, webhook_url.as_ref()) {
        let text = format!("{} [{}] {} — {}", label, symbol, alert.kind, alert.message);
        let raw = serde_json::json!({
            "text": text, "ts": ts, "symbol": symbol, "action": "alert",
            "kind": alert.kind, "firing": alert.firing, "message": alert.message,
        });
        let body = webhook_body(webhook_format, &text, &raw);
        tokio::spawn(post_webhook(client.clone(), url.clone(), body));
    }
}

/// Handle maker commands
pub async fn handle_maker(
    command: MakerCommands,
    output_format: OutputFormat,
    verbose: bool,
) -> Result<()> {
    match command {
        MakerCommands::Run {
            symbol,
            maker_config,
            spread_bps,
            band_bps,
            size,
            levels,
            level_step_bps,
            refresh_bps,
            interval,
            max_position,
            skew_bps,
            inventory_exit_pct,
            inventory_exit_qty,
            max_divergence_bps,
            vol_pause_bps,
            vol_window,
            alert_loss,
            alert_inventory_pct,
            alert_uptime,
            alert_webhook,
            alert_webhook_format,
            no_ws,
            live,
            controlled_disconnect_after,
        } => {
            let file = config::load(maker_config.as_deref())?;
            run_maker(
                symbol,
                MakerRunArgs {
                    spread_bps: choose(spread_bps, file.spread_bps, 5.0),
                    band_bps: choose(band_bps, file.band_bps, 20.0),
                    size: choose(size, file.size, 0.01),
                    levels: choose(levels, file.levels, 1),
                    level_step_bps: choose(level_step_bps, file.level_step_bps, 2.0),
                    refresh_bps: choose(refresh_bps, file.refresh_bps, 3.0),
                    interval: choose(interval, file.interval, 5),
                    max_position: choose(max_position, file.max_position, 0.05),
                    skew_bps: choose(skew_bps, file.skew_bps, 0.0),
                    inventory_exit_pct: choose(inventory_exit_pct, file.inventory_exit_pct, 0.0),
                    inventory_exit_qty: choose(inventory_exit_qty, file.inventory_exit_qty, 0.0),
                    max_divergence_bps: choose(max_divergence_bps, file.max_divergence_bps, 25.0),
                    vol_pause_bps: choose(vol_pause_bps, file.vol_pause_bps, 0.0),
                    vol_window: choose(vol_window, file.vol_window, 12),
                    alert_loss: choose(alert_loss, file.alert_loss, 0.0),
                    alert_inventory_pct: choose(alert_inventory_pct, file.alert_inventory_pct, 0.0),
                    alert_uptime: choose(alert_uptime, file.alert_uptime, 0.0),
                    alert_webhook,
                    alert_webhook_format,
                    no_ws: no_ws || file.no_ws.unwrap_or(false),
                    live,
                    controlled_disconnect_after,
                    verbose,
                },
                output_format,
            )
            .await
        }
    }
}

fn choose<T: Copy>(cli: Option<T>, file: Option<T>, default: T) -> T {
    cli.or(file).unwrap_or(default)
}

struct MakerRunArgs {
    spread_bps: f64,
    band_bps: f64,
    size: f64,
    levels: u32,
    level_step_bps: f64,
    refresh_bps: f64,
    interval: u64,
    max_position: f64,
    skew_bps: f64,
    inventory_exit_pct: f64,
    inventory_exit_qty: f64,
    max_divergence_bps: f64,
    vol_pause_bps: f64,
    vol_window: u32,
    alert_loss: f64,
    alert_inventory_pct: f64,
    alert_uptime: f64,
    alert_webhook: Option<String>,
    alert_webhook_format: AlertWebhookFormat,
    no_ws: bool,
    live: bool,
    controlled_disconnect_after: Option<u64>,
    verbose: bool,
}

async fn run_maker(symbol: String, args: MakerRunArgs, output_format: OutputFormat) -> Result<()> {
    use standx_sdk::order_response::OrderResponseStream;

    let order_session_id = args.live.then(|| uuid::Uuid::new_v4().to_string());

    if let Some(after) = args.controlled_disconnect_after {
        if !args.live {
            return Err(anyhow::anyhow!(
                "--controlled-disconnect-after requires --live"
            ));
        }
        if after == 0 || after > 60 {
            return Err(anyhow::anyhow!(
                "--controlled-disconnect-after must be between 1 and 60 seconds"
            ));
        }
    }
    let client = match order_session_id.as_deref() {
        Some(session_id) => StandXClient::new()?.with_session_id(session_id),
        None => StandXClient::new()?,
    };

    // ---- Startup: symbol metadata + invariants (fail fast) ----
    let infos = client.get_symbol_info().await?;
    let info = infos
        .iter()
        .find(|i| i.symbol.eq_ignore_ascii_case(&symbol))
        .ok_or_else(|| {
            anyhow::anyhow!(
                "Unknown symbol '{}'. Available: {}",
                symbol,
                infos
                    .iter()
                    .map(|i| i.symbol.as_str())
                    .collect::<Vec<_>>()
                    .join(", ")
            )
        })?;
    if info.status != "trading" {
        return Err(anyhow::anyhow!(
            "Symbol {} is not trading (status: {})",
            info.symbol,
            info.status
        ));
    }
    let symbol = info.symbol.clone(); // canonical casing

    let min_order_qty: f64 = info.min_order_qty.parse().unwrap_or(0.0);
    let cfg = MakerConfig {
        spread_bps: args.spread_bps,
        band_bps: args.band_bps,
        level_step_bps: args.level_step_bps,
        refresh_bps: args.refresh_bps,
        levels: args.levels.max(1),
        size: args.size,
        max_position: args.max_position,
        skew_bps: args.skew_bps,
        price_decimals: info.price_tick_decimals,
        qty_decimals: info.qty_tick_decimals,
        min_order_qty,
    };

    if cfg.spread_bps <= 0.0 {
        return Err(anyhow::anyhow!("--spread-bps must be > 0"));
    }
    if cfg.skew_bps < 0.0 {
        return Err(anyhow::anyhow!("--skew-bps must be >= 0"));
    }
    if !(0.0..=100.0).contains(&args.inventory_exit_pct) || args.inventory_exit_qty < 0.0 {
        return Err(anyhow::anyhow!(
            "--inventory-exit-pct must be 0..=100 and --inventory-exit-qty must be >= 0"
        ));
    }
    if (args.inventory_exit_pct > 0.0) != (args.inventory_exit_qty > 0.0) {
        return Err(anyhow::anyhow!(
            "active inventory exit requires both --inventory-exit-pct and --inventory-exit-qty"
        ));
    }
    if cfg.band_bps <= cfg.spread_bps {
        return Err(anyhow::anyhow!(
            "--band-bps ({}) must be greater than --spread-bps ({}): quotes clamped to the band edge would sit exactly at the boundary",
            cfg.band_bps,
            cfg.spread_bps
        ));
    }
    let rounded_size = maker::round_to_decimals(cfg.size, cfg.qty_decimals);
    if rounded_size < cfg.min_order_qty || rounded_size <= 0.0 {
        return Err(anyhow::anyhow!(
            "--size {} (rounded to {} at {} decimals) is below min order qty {} for {}",
            cfg.size,
            rounded_size,
            cfg.qty_decimals,
            cfg.min_order_qty,
            symbol
        ));
    }
    if cfg.refresh_bps >= cfg.spread_bps {
        eprintln!(
            "⚠️  --refresh-bps ({}) >= --spread-bps ({}): quotes will be held through large drifts",
            cfg.refresh_bps, cfg.spread_bps
        );
    }
    if cfg.levels > 1
        && cfg.spread_bps + (cfg.levels - 1) as f64 * cfg.level_step_bps >= cfg.band_bps
    {
        eprintln!("⚠️  outer quote levels exceed the band and will be clamped/collapsed");
    }

    // ---- Live gating & clean start ----
    let mut order_responses = None;
    let mut order_response_health = None;
    let mut order_response_handle = None;
    if args.live {
        if std::env::var(LIVE_MAKER_ENV).ok().as_deref() != Some("1") {
            return Err(anyhow::anyhow!(
                "live mode not yet enabled: it has not been supervised-tested against production. Set {}=1 to unlock (at your own risk).",
                LIVE_MAKER_ENV
            ));
        }
        let creds = Credentials::load()?;
        if creds.is_expired() {
            return Err(anyhow::anyhow!(
                "Credentials expired. Run 'standx auth login' first."
            ));
        }
        if creds.private_key.is_empty() {
            return Err(anyhow::anyhow!(
                "Live mode requires a private key for order signing. Run 'standx auth login' with --private-key."
            ));
        }
        let open_orders = client.get_open_orders(Some(&symbol)).await?;
        let manual_orders = open_orders
            .iter()
            .filter(|order| !is_maker_order(order))
            .count();
        if manual_orders > 0 {
            eprintln!(
                "ℹ️  preserving {} manually-managed order(s) on {}; only {} orders are managed",
                manual_orders, symbol, MAKER_CL_ORD_ID_PREFIX
            );
        }
        // Clean only leftover orders owned by this maker. Manual/API orders
        // are not part of the strategy's reconciliation state and must never
        // be adopted or cancelled as stale.
        cancel_maker_orders_with_retry(&client, &symbol, 3, output_format).await?;

        let stream = OrderResponseStream::new(
            order_session_id
                .as_deref()
                .expect("live maker must have an order session"),
        )?;
        let (responses, health, handle) = stream.connect().await?;
        if let Some(after) = args.controlled_disconnect_after {
            let health_for_fault = health.clone();
            let abort = handle.abort_handle();
            tokio::spawn(async move {
                tokio::time::sleep(Duration::from_secs(after)).await;
                // Aborting drops the local WebSocket halves; set health first
                // so the maker exits through its existing fail-safe path even
                // if the runtime delays observing the socket close.
                health_for_fault.mark_unhealthy(format!(
                    "controlled fault injection closed the order-response stream after {after}s"
                ));
                abort.abort();
            });
            eprintln!(
                "⚠️ controlled fault injection armed: closing order-response stream after {after}s"
            );
        }
        order_responses = Some(responses);
        order_response_health = Some(health);
        order_response_handle = Some(handle);
    }

    let mode = if args.live { "LIVE" } else { "PAPER" };
    if output_format == OutputFormat::Table {
        println!("┌──────────────────────────────────────────────────────────┐");
        println!("│ standx maker — {} mode on {}", mode, symbol);
        println!(
            "│ spread {}bps | band {}bps | refresh {}bps | {} level(s)",
            cfg.spread_bps, cfg.band_bps, cfg.refresh_bps, cfg.levels
        );
        println!(
            "│ size {} | max-position {} | interval {}s",
            cfg.size, cfg.max_position, args.interval
        );
        if cfg.skew_bps > 0.0 {
            println!(
                "│ inventory skew {}bps (live only; paper holds no position)",
                cfg.skew_bps
            );
        }
        if args.inventory_exit_pct > 0.0 {
            println!(
                "│ active exit: {}% of max, reduce-only chunks of {} (live only)",
                args.inventory_exit_pct, args.inventory_exit_qty
            );
        }
        println!(
            "│ ticks: price {}dp, qty {}dp | min qty {}",
            cfg.price_decimals, cfg.qty_decimals, cfg.min_order_qty
        );
        if !args.live {
            println!("│ paper mode: no real orders; fills are simulated when the");
            println!("│ touch crosses a quote, so position & skew move. --live for real.");
        } else {
            println!(
                "│ ⚠️  LIVE: the bot manages only {} orders on {}",
                MAKER_CL_ORD_ID_PREFIX, symbol
            );
            println!("│ manual/API orders are preserved and ignored.");
        }
        if args.no_ws {
            println!("│ feed: REST polling (--no-ws)");
        } else {
            println!(
                "│ feed: websocket (REST fallback) | divergence guard {}bps",
                args.max_divergence_bps
            );
        }
        if args.vol_pause_bps > 0.0 {
            println!(
                "│ vol breaker: halt at {}bps range / {} cycles (resume < {}bps)",
                args.vol_pause_bps,
                args.vol_window.max(1),
                args.vol_pause_bps / 2.0
            );
        }
        if args.alert_loss > 0.0 || args.alert_inventory_pct > 0.0 || args.alert_uptime > 0.0 {
            let mut parts = Vec::new();
            if args.alert_loss > 0.0 {
                parts.push(format!("loss -{}", args.alert_loss));
            }
            if args.alert_inventory_pct > 0.0 {
                parts.push(format!("inv {}%", args.alert_inventory_pct));
            }
            if args.alert_uptime > 0.0 {
                parts.push(format!("uptime {}%", args.alert_uptime));
            }
            let sink = if args.alert_webhook.is_some() {
                format!("stderr + webhook ({:?})", args.alert_webhook_format).to_lowercase()
            } else {
                "stderr".to_string()
            };
            println!("│ risk alerts: {} → {}", parts.join(", "), sink);
        }
        println!("│ Ctrl+C to stop (cancels maker-owned resting orders on exit)");
        println!("└──────────────────────────────────────────────────────────┘");
    }

    // Webhook client (also carries lifecycle + risk-alert messages).
    let alert_http = args.alert_webhook.as_ref().map(|_| reqwest::Client::new());

    // Notify start (fire-and-forget; the process keeps running).
    notify_lifecycle(
        "started",
        &format!(
            "🟢 maker started — {} {} | spread {}bps band {}bps size {} | {}",
            mode,
            symbol,
            cfg.spread_bps,
            cfg.band_bps,
            cfg.size,
            if args.no_ws { "REST" } else { "WS" }
        ),
        &symbol,
        output_format,
        alert_http.as_ref(),
        &args.alert_webhook,
        args.alert_webhook_format,
        false,
    )
    .await;

    // ---- Market feed (WS primary, REST fallback) ----
    let (feed, mut updates, feed_handle) = if args.no_ws {
        (None, None, None)
    } else {
        let (state, rx, handle) = spawn_market_feed(symbol.clone(), args.verbose);
        (Some(state), Some(rx), Some(handle))
    };

    // ---- Loop state ----
    let mut cycle: u64 = 0;
    let mut resting: Vec<RestingQuote> = Vec::new(); // paper-mode book
    let mut adopted: HashMap<String, (u32, f64, u64)> = HashMap::new(); // id -> (level, ref_mark, cycle)
    let mut pending: Vec<PendingPlace> = Vec::new();
    let mut inventory_exit_pending = false;
    let mut maker_order_ids: HashSet<u64> = HashSet::new();
    let mut seen_fill_ids: HashSet<u64> = HashSet::new();
    let session_started_at = chrono::Utc::now().timestamp();
    let mut consecutive_errors: u32 = 0;
    let mut total_places: u64 = 0;
    let mut total_cancels: u64 = 0;
    let mut total_holds: u64 = 0;
    let mut total_fills: u64 = 0;
    let mut total_halted: u64 = 0;
    let mut sim_position: f64 = 0.0; // paper-mode simulated inventory
    let mut stats = MakerStats::default();
    let mut breaker = VolBreaker::new(args.vol_window.max(1) as usize, args.vol_pause_bps);
    let mut alerts =
        AlertMonitor::new(args.alert_loss, args.alert_inventory_pct, args.alert_uptime);
    let mut last_mark: Option<f64> = None;
    let mut last_src: Option<&'static str> = None;

    let exit = 'main: loop {
        if args.live {
            if let Some(health) = order_response_health
                .as_ref()
                .filter(|health| !health.is_healthy())
            {
                let detail = health.failure_reason().unwrap_or_else(|| {
                    "order-response stream became unhealthy without a recorded reason".to_string()
                });
                break MakerExit::OrderResponse(format!("{detail}; refusing further live orders"));
            }
        }
        if let Some(receiver) = order_responses.as_mut() {
            if let Err(error) = apply_order_responses(
                receiver,
                &mut pending,
                output_format,
                &symbol,
                cycle,
                cfg.price_decimals,
            ) {
                break MakerExit::OrderResponse(error.to_string());
            }
        }

        // Work phase raced against Ctrl+C so a slow API call can be
        // interrupted (mirrors run_watch_loop).
        let work = async {
            let (mark, best_bid, best_ask, src) =
                market_snapshot(&client, &symbol, feed.as_ref()).await?;
            let (places, cancels, holds, fills) = maker_cycle(
                &client,
                &symbol,
                &cfg,
                args.live,
                cycle,
                mark,
                best_bid,
                best_ask,
                args.max_divergence_bps,
                args.inventory_exit_pct,
                args.inventory_exit_qty,
                &mut resting,
                &mut adopted,
                &mut pending,
                &mut inventory_exit_pending,
                &mut maker_order_ids,
                &mut seen_fill_ids,
                session_started_at,
                &mut sim_position,
                &mut stats,
                &mut breaker,
                output_format,
                order_response_health.as_ref(),
            )
            .await?;
            Ok::<_, anyhow::Error>((places, cancels, holds, fills, mark, src, breaker.halted()))
        };
        let cycle_result = tokio::select! {
            _ = signal::ctrl_c() => break MakerExit::CtrlC,
            result = work => result,
        };

        match cycle_result {
            Ok((places, cancels, holds, fills, mark, src, halted)) => {
                consecutive_errors = 0;
                total_places += places;
                total_cancels += cancels;
                total_holds += holds;
                total_fills += fills;
                total_halted += halted as u64;
                last_mark = Some(mark);
                if !args.no_ws && last_src != Some(src) {
                    match src {
                        "ws" => eprintln!("✅ market feed: websocket live"),
                        _ => eprintln!(
                            "⚠️  market feed: REST fallback (websocket warming up or stale)"
                        ),
                    }
                    last_src = Some(src);
                }
                // Risk alerts: evaluate over the just-updated stats and
                // deliver any state changes (stderr always; webhook if set).
                if alerts.enabled() {
                    let fired =
                        alerts.evaluate(&stats, stats.position(), mark, cfg.max_position, cycle);
                    for alert in fired {
                        deliver_alert(
                            &alert,
                            &symbol,
                            output_format,
                            alert_http.as_ref(),
                            &args.alert_webhook,
                            args.alert_webhook_format,
                        );
                    }
                }
            }
            Err(e) => {
                consecutive_errors += 1;
                eprintln!("⚠️  maker cycle failed ({}/3): {}", consecutive_errors, e);
                if consecutive_errors >= 3 {
                    break MakerExit::ConsecutiveErrors(e.to_string());
                }
            }
        }

        cycle += 1;

        // Sleep until the next cycle, but wake early when the cached mark
        // has already drifted beyond refresh_bps — the quotes would be
        // re-quoted anyway, so reacting now shrinks the pick-off window
        // without adding flicker. min-gap of 1s bounds the API rate.
        let deadline = tokio::time::Instant::now() + Duration::from_secs(args.interval);
        let min_gap = tokio::time::Instant::now() + Duration::from_secs(1);
        loop {
            let update = async {
                match updates.as_mut() {
                    Some(rx) => rx.changed().await.is_ok(),
                    None => std::future::pending().await,
                }
            };
            tokio::select! {
                _ = signal::ctrl_c() => break 'main MakerExit::CtrlC,
                _ = tokio::time::sleep_until(deadline) => break,
                ok = update => {
                    if !ok {
                        // Feed task gone: fall back to plain interval waits.
                        updates = None;
                        continue;
                    }
                    if tokio::time::Instant::now() < min_gap {
                        continue;
                    }
                    let (Some(feed), Some(prev)) = (feed.as_ref(), last_mark) else {
                        continue;
                    };
                    let drifted = {
                        let s = feed.read().await;
                        s.mark
                            .is_some_and(|m| maker::bps_diff(m, prev) > cfg.refresh_bps)
                    };
                    if drifted {
                        break; // early re-quote cycle
                    }
                }
            }
        }
    };

    // ---- Cleanup on ALL exit paths ----
    if let Some(handle) = feed_handle {
        handle.abort();
    }
    if output_format == OutputFormat::Table {
        println!(
            "\n👋 Stopping maker (ran {} cycles: {} places, {} cancels, {} holds)",
            cycle, total_places, total_cancels, total_holds
        );
        let pnl_note = match last_mark {
            Some(m) => format!(" | PnL {:+.2} (mark-to-market)", stats.mark_to_market(m)),
            None => String::new(),
        };
        println!(
            "   {} fills | uptime {:.0}% | max pos {} | avg capture {:.1}bps{}",
            total_fills,
            stats.uptime_pct(),
            maker::format_decimals(stats.max_abs_position, cfg.qty_decimals),
            stats.avg_spread_capture_bps(),
            pnl_note
        );
        if breaker.enabled() {
            println!("   vol breaker: {} cycles halted", total_halted);
        }
        if !args.live {
            println!(
                "   paper sim: ending position {}",
                maker::format_decimals(sim_position, cfg.qty_decimals)
            );
        }
    }
    if let Some(handle) = order_response_handle {
        handle.abort();
    }
    // Do not return early on cleanup failure: operators need the stopped
    // lifecycle alert most when residual maker orders may still be live.
    let cleanup_error = if args.live {
        cancel_maker_orders_with_retry(&client, &symbol, 3, output_format)
            .await
            .err()
    } else {
        None
    };

    // Notify stop on every exit path. Await delivery so the message lands
    // before the process exits.
    let reason = exit.lifecycle_reason();
    let pnl_str = last_mark
        .map(|m| format!("{:+.2}", stats.mark_to_market(m)))
        .unwrap_or_else(|| "n/a".to_string());
    let cleanup_note = cleanup_error.as_ref().map_or_else(String::new, |error| {
        format!(" | ⚠️ cleanup failed: {error}")
    });
    notify_lifecycle(
        "stopped",
        &format!(
            "🔴 maker stopped ({}) — {} | {} cycles, {} fills, uptime {:.0}%, PnL {}{}",
            reason,
            symbol,
            cycle,
            total_fills,
            stats.uptime_pct(),
            pnl_str,
            cleanup_note,
        ),
        &symbol,
        output_format,
        alert_http.as_ref(),
        &args.alert_webhook,
        args.alert_webhook_format,
        true,
    )
    .await;

    if let Some(error) = cleanup_error {
        return Err(anyhow::anyhow!(
            "maker stopped but maker-owned order cleanup failed: {}",
            error
        ));
    }

    match exit.terminal_error() {
        Some(message) => Err(anyhow::anyhow!(message)),
        None => Ok(()),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use mockito::{Matcher, Server};

    #[test]
    fn order_response_exit_message_does_not_claim_three_errors() {
        let exit = MakerExit::OrderResponse(
            "order-response WebSocket closed: code=1008 reason=\"maintenance\"".to_string(),
        );

        let lifecycle = exit.lifecycle_reason();
        let terminal = exit.terminal_error().unwrap();
        assert!(lifecycle.contains("code=1008"), "{lifecycle}");
        assert!(terminal.contains("stopped immediately"), "{terminal}");
        assert!(!terminal.contains("3 consecutive"), "{terminal}");
    }

    #[test]
    fn consecutive_cycle_exit_message_names_three_errors() {
        let exit = MakerExit::ConsecutiveErrors("network timeout".to_string());

        let lifecycle = exit.lifecycle_reason();
        let terminal = exit.terminal_error().unwrap();
        assert!(lifecycle.contains("3 consecutive maker cycle errors"));
        assert!(terminal.contains("3 consecutive maker cycle errors"));
    }

    struct EnvGuard {
        key: &'static str,
        original: Option<String>,
    }

    impl EnvGuard {
        fn set(key: &'static str, value: &str) -> Self {
            let original = std::env::var(key).ok();
            std::env::set_var(key, value);
            Self { key, original }
        }
    }

    impl Drop for EnvGuard {
        fn drop(&mut self) {
            match &self.original {
                Some(value) => std::env::set_var(self.key, value),
                None => std::env::remove_var(self.key),
            }
        }
    }

    #[test]
    fn webhook_body_shapes() {
        let txt = "🚨 ALERT [BTC-USD] loss — PnL -50 breached";
        // Structured object a caller would build for the Raw format.
        let raw_in = serde_json::json!({
            "text": txt, "symbol": "BTC-USD", "kind": "loss", "firing": true,
        });

        // Slack / Telegram: bare {"text": ...}
        let slack = webhook_body(AlertWebhookFormat::Slack, txt, &raw_in);
        assert_eq!(slack["text"], txt);
        assert!(slack.get("msg_type").is_none());
        let tg = webhook_body(AlertWebhookFormat::Telegram, txt, &raw_in);
        assert_eq!(tg["text"], txt);
        assert!(tg.get("kind").is_none()); // not the structured object

        // Feishu: {"msg_type":"text","content":{"text":...}}
        let feishu = webhook_body(AlertWebhookFormat::Feishu, txt, &raw_in);
        assert_eq!(feishu["msg_type"], "text");
        assert_eq!(feishu["content"]["text"], txt);

        // Raw: the structured object verbatim.
        let raw = webhook_body(AlertWebhookFormat::Raw, txt, &raw_in);
        assert_eq!(raw["kind"], "loss");
        assert_eq!(raw["firing"], true);
        assert_eq!(raw["symbol"], "BTC-USD");
    }

    #[test]
    fn business_rejection_not_fail_safe() {
        // Post-only would-cross / order-not-found: exchange said no.
        assert!(is_order_rejection(&StandxError::Api {
            code: 400,
            message: "post-only would cross".into(),
            endpoint: None,
            retryable: false,
        }));
        // 5xx from the venue: transient → counts toward fail-safe.
        assert!(!is_order_rejection(&StandxError::Api {
            code: 502,
            message: "bad gateway".into(),
            endpoint: None,
            retryable: true,
        }));
        // Network layer: transient → counts toward fail-safe.
        assert!(!is_order_rejection(&StandxError::Http {
            code: 0,
            message: "connection reset".into(),
            retryable: Some(true),
        }));
    }

    #[test]
    fn partial_fill_stays_adopted() {
        // Full remainder adopts.
        assert!(open_qty_adopts(0.01, 0.01));
        // Partial remainder (half filled) still adopts.
        assert!(open_qty_adopts(0.005, 0.01));
        // Tiny remainder adopts.
        assert!(open_qty_adopts(0.0001, 0.01));
        // Zero / fully filled does not adopt (no open order to match).
        assert!(!open_qty_adopts(0.0, 0.01));
        // Larger than placed is someone else's order.
        assert!(!open_qty_adopts(0.02, 0.01));
        // Float slop just under the placed qty is tolerated.
        assert!(open_qty_adopts(0.01 + 1e-9, 0.01));
    }

    #[test]
    fn maker_order_ownership_uses_reserved_client_id_prefix() {
        let order = |cl_ord_id: Option<&str>| Order {
            id: "123".to_string(),
            cl_ord_id: cl_ord_id.map(str::to_string),
            symbol: "BTC-USD".to_string(),
            side: OrderSide::Buy,
            order_type: standx_sdk::models::OrderType::Limit,
            qty: "0.01".to_string(),
            fill_qty: "0".to_string(),
            price: "100".to_string(),
            status: standx_sdk::models::OrderStatus::New,
            created_at: "now".to_string(),
            updated_at: "now".to_string(),
        };

        assert!(is_maker_order(&order(Some("sxmk-7f2b"))));
        assert!(!is_maker_order(&order(Some("manual-7f2b"))));
        assert!(!is_maker_order(&order(None)));
    }

    #[test]
    fn pending_order_reserves_its_quote_slot() {
        let pending = vec![PendingPlace {
            request_id: "request-1".to_string(),
            cl_ord_id: "sxmk-1".to_string(),
            side: OrderSide::Buy,
            price: 100.0,
            qty: 0.01,
            level: 0,
            ref_center: 100.0,
            cycle: 1,
        }];

        assert!(pending_covers_slot(&pending, OrderSide::Buy, 0));
        assert!(!pending_covers_slot(&pending, OrderSide::Buy, 1));
        assert!(!pending_covers_slot(&pending, OrderSide::Sell, 0));
    }

    #[test]
    fn cli_value_overrides_maker_file_then_default() {
        assert_eq!(choose(Some(3_u32), Some(2), 1), 3);
        assert_eq!(choose(None, Some(2_u32), 1), 2);
        assert_eq!(choose(None::<u32>, None, 1), 1);
    }

    #[test]
    fn async_rejection_removes_only_matching_pending_place() {
        let (sender, mut receiver) = tokio::sync::mpsc::channel(4);
        let pending_place = |request_id: &str| PendingPlace {
            request_id: request_id.to_string(),
            cl_ord_id: format!("client-{request_id}"),
            side: OrderSide::Buy,
            price: 100.0,
            qty: 0.01,
            level: 0,
            ref_center: 100.0,
            cycle: 1,
        };
        let mut pending = vec![pending_place("request-1"), pending_place("request-2")];
        sender
            .try_send(OrderResponse {
                code: 400,
                message: "alo order rejected".to_string(),
                request_id: Some("request-1".to_string()),
            })
            .unwrap();

        apply_order_responses(
            &mut receiver,
            &mut pending,
            OutputFormat::Quiet,
            "BTC-USD",
            2,
            2,
        )
        .unwrap();

        assert_eq!(pending.len(), 1);
        assert_eq!(pending[0].request_id, "request-2");
    }

    #[test]
    fn async_acceptance_keeps_pending_until_exchange_order_is_visible() {
        let (sender, mut receiver) = tokio::sync::mpsc::channel(2);
        let mut pending = vec![PendingPlace {
            request_id: "request-1".to_string(),
            cl_ord_id: "client-1".to_string(),
            side: OrderSide::Sell,
            price: 101.0,
            qty: 0.01,
            level: 0,
            ref_center: 100.0,
            cycle: 1,
        }];
        sender
            .try_send(OrderResponse {
                code: 0,
                message: "accepted".to_string(),
                request_id: Some("request-1".to_string()),
            })
            .unwrap();

        apply_order_responses(
            &mut receiver,
            &mut pending,
            OutputFormat::Quiet,
            "BTC-USD",
            2,
            2,
        )
        .unwrap();

        assert_eq!(pending.len(), 1);
    }

    #[test]
    fn disconnected_order_response_stream_is_fail_closed() {
        let (sender, mut receiver) = tokio::sync::mpsc::channel(1);
        drop(sender);
        let mut pending = Vec::new();

        let error = apply_order_responses(
            &mut receiver,
            &mut pending,
            OutputFormat::Quiet,
            "BTC-USD",
            1,
            2,
        )
        .unwrap_err();

        assert!(error.to_string().contains("disconnected"));
    }

    #[tokio::test]
    async fn controlled_disconnect_fails_closed_then_cleans_only_maker_orders() {
        let (sender, mut receiver) = tokio::sync::mpsc::channel(1);
        drop(sender);
        let mut pending = Vec::new();

        let error = apply_order_responses(
            &mut receiver,
            &mut pending,
            OutputFormat::Quiet,
            "BTC-USD",
            7,
            2,
        )
        .unwrap_err();
        assert!(error.to_string().contains("disconnected"));
        eprintln!("controlled disconnect -> fail-safe: {error}");

        let _jwt = EnvGuard::set("STANDX_JWT", "controlled-test-jwt");
        let mut server = Server::new_async().await;
        let open_before = server
            .mock("GET", "/api/query_open_orders")
            .match_query(Matcher::UrlEncoded("symbol".into(), "BTC-USD".into()))
            .with_status(200)
            .with_header("content-type", "application/json")
            .with_body(
                r#"{"code":0,"message":"ok","result":[
                    {"id":"42","cl_ord_id":"sxmk-controlled-buy","symbol":"BTC-USD","side":"buy","order_type":"limit","qty":"0.001","fill_qty":"0","price":"63000","status":"open","created_at":"2026-07-10T00:00:00Z","updated_at":"2026-07-10T00:00:00Z"},
                    {"id":"99","cl_ord_id":"manual-order","symbol":"BTC-USD","side":"sell","order_type":"limit","qty":"0.001","fill_qty":"0","price":"65000","status":"open","created_at":"2026-07-10T00:00:00Z","updated_at":"2026-07-10T00:00:00Z"}
                ]}"#,
            )
            .expect(1)
            .create_async()
            .await;
        let cancel = server
            .mock("POST", "/api/cancel_orders")
            .match_body(Matcher::Json(serde_json::json!({ "order_id_list": [42] })))
            .with_status(200)
            .with_header("content-type", "application/json")
            .with_body(r#"{"code":0,"message":"accepted"}"#)
            .expect(1)
            .create_async()
            .await;
        let open_after = server
            .mock("GET", "/api/query_open_orders")
            .match_query(Matcher::UrlEncoded("symbol".into(), "BTC-USD".into()))
            .with_status(200)
            .with_header("content-type", "application/json")
            .with_body(
                r#"{"code":0,"message":"ok","result":[
                    {"id":"99","cl_ord_id":"manual-order","symbol":"BTC-USD","side":"sell","order_type":"limit","qty":"0.001","fill_qty":"0","price":"65000","status":"open","created_at":"2026-07-10T00:00:00Z","updated_at":"2026-07-10T00:00:00Z"}
                ]}"#,
            )
            .expect(1)
            .create_async()
            .await;

        let client = StandXClient::with_base_url(server.url()).unwrap();
        cancel_maker_orders_with_retry(&client, "BTC-USD", 3, OutputFormat::Quiet)
            .await
            .unwrap();

        open_before.assert_async().await;
        cancel.assert_async().await;
        open_after.assert_async().await;
    }
}
